### ISSUE TITLE
potplayer_advanced.py  放进去没有变化啊

### ISSUE THREAD

**Issue by ZJDATY** [xfangfang/Macast-plugins#7]
这个py要和  potplaye.py要放一起吗 加不加这个文件看起来没有什么变化呢 路径已经修改了   potplaye.py是正常使用的 potplayer_advanced.py这个文件放进去 软件并没有看到出现高级设置

**Comment by xfangfang** [comment]
potplayer_advanced.py 需要搭配测试版Macast使用（https://github.com/xfangfang/Macast/actions），我提前传过来给大家预览的。

支持手机端控制播放暂停、拖拽进度、弹幕显示、自动查找potplayer安装目录等功能

**Comment by ZJDATY** [comment]
> potplayer_advanced.py 需要配合[版Macast](https://github.com/xfangfang/Macast/actions)使用，我提前传过来给大家测试的。
> 
> 支持手机端控制播放暂停、拖拖显示、弹幕显示、自动查找potplayer安装目录等功能

好的 懂了

**Comment by xfangfang** [comment]
如果没有其他问题，可以关闭这个issue了
